### ISSUE TITLE
add md support to renderer.js

### ISSUE THREAD

**Issue by afincato** [nonlinear-thinkering-group/pask#1]
think all we need is `link` support, and sure `italic` and `bold` etc to be fancy. 

so i wonder if we actually need something like [markdown-it](https://github.com/markdown-it/markdown-it), or [any other](https://github.com/sparksuite/simplemde-markdown-editor) markdown parser; or if we can write  a couple of regexes instead.

also it depends on the scope of the chat itself. because inline images would be super fancy.

and like if we start using it to discuss properly etc, maybe even list items would be nice.

**Comment by goodnekk** [comment]
It depends a bit I think on weather we want to use it more for full paragraphs of text or more for short chat-like sentences. It shouldn't be too hard to put a markdown parser. We could implement it also in a "block" type style. For example images could be done like this:
`/image cats.jpg`

**Comment by afincato** [comment]
line 13 seems where to hook in the md parser right? i can try later.

https://github.com/nonlinear-thinkering-group/pask/blob/master/renderer.js#L13

**Comment by goodnekk** [comment]
Exactly. Mithril requires an extra function for inserting literal html, it would look something like this:
`m("span.message-text", m.trust( markdownparser(message.text) )) `

**Comment by afincato** [comment]
1. where do i tell the electron app to open links through the os default browser?
2. i like the `/image` block, but think that beside giving the chance to add inline images through the md syntax (now working and displaying properly), we should maybe either get rid or integrate the `/image` syntax with a drop-in action? eg. you drag and drop a file from your computer onto the input bar and either you add before `/image` or it does it automatically and then the app copies that file over the dat archive as well and it gets rendered through the markdown parser or whatever...

thoughts?

i'd say then it should not be more that this for now. i like the spareness of it, like being focus on being chatty rather than long-form texty. we can do that on a git repo indeed.

**Comment by goodnekk** [comment]
1. you need to set `target="_blank"` on the link. I think this should do it: https://github.com/crookedneighbor/markdown-it-link-attributes
2. In that case I would just get the image drag and drop to replace with the markdown syntax. :)

**Comment by goodnekk** [comment]
I did add that to the latest commit, did you merge?

**Comment by sonn-gamm** [comment]
oh yeah i was still in the `md` branch, it's working now! i pushed it to the master.

**Comment by wolkenmachine** [comment]
awesome!
